name: oag_food_ui
description: "Showcase project for a Food application that would display food recommendations. Primarily, this project is to showcase UI and animations."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/beef_stew.jpg
    - assets/images/italian_pasta.jpg
    - assets/images/chicken_caesar_salad.png
    - assets/images/cooking.png
    - assets/images/cooking (1).png
    - assets/images/food.png
    - assets/images/logo.png
    - assets/images/logo (1).png
    - assets/images/main_background.jpeg
    - assets/images/sky_1920x1280.jpg

    - assets/images/category/bread.png
    - assets/images/category/carrot.png
    - assets/images/category/cheese.png
    - assets/images/category/chicken.png
    - assets/images/category/fish.png
    - assets/images/category/lettuce.png
    - assets/images/category/meat.png
    - assets/images/category/mayonnaise.png
    - assets/images/category/mushroom.png
    - assets/images/category/olive.png
    - assets/images/category/olive_oil.png
    - assets/images/category/pasta.png
    - assets/images/category/potato.png
    - assets/images/category/tomato.png
    - assets/images/category/salami.png
    - assets/images/category/vegetable.png

    - assets/images/icon/ingredient.png
    - assets/images/icon/bubble_outlined.png
    - assets/images/icon/bubble_solid.png
